### ISSUE TITLE
Loading model... Error reading Obj file! Segmentation fault

### ISSUE THREAD

**Issue by CESI2Jaafar** [PRBonn/fast_change_detection#2]
With the below two errors, I could run your models.
![image](https://user-images.githubusercontent.com/128801324/233392048-3ba85e18-eb20-49b8-b660-f01674d9f41c.png)
![image](https://user-images.githubusercontent.com/128801324/233393845-9857d58c-8fb8-464a-bea9-31d7d7148fe4.png)
When, I start running my model which is digital twin of a lab, I get this error:
`OpenGL Context Version 3.3 core profile
GLEW initialized.
OpenGL context version: 3.3
OpenGL vendor string  : Microsoft Corporation
OpenGL renderer string: D3D12 (NVIDIA GeForce RTX 2080)
Loading model... Error reading Obj file!
Segmentation fault`

**Comment by Eman7C7** [comment]
Hi, sorry for the late response. It looks like a problem of the parser. It's been a lot and don't remember the code well, but I guess you can see what's wrong somewhere in https://github.com/PRBonn/fast_change_detection/blob/master/src/utils/obj_reader.cpp. You can try printing the actual exception here https://github.com/PRBonn/fast_change_detection/blob/master/src/example.cpp#L31, rather than the generic error... One simple question: is the data named correctly (in a structure similar to my dataset)?

**Comment by CESI2Jaafar** [comment]
Hi, Your response is highly apprecaited! Yes everything like yours and I have checked with notepad++. Also they are similar. I could open one and just it does show a part of 3D obj not entire of that. If run again, it does not works. Sound magic

**Comment by CESI2Jaafar** [comment]
Just a easy question does groun_turth has affect on?

**Comment by Eman7C7** [comment]
No, ground_truth is for evaluation. The software doesn't require it.

The two things I suggests are:
- try simplifying the mesh to verify that it's not a memory problem
- try printing the original exception of the obj reader instead of the caught one by the example program
